name: Node.js CI and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]  # Bạn có thể thêm nhiều phiên bản nếu cần

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci  # Clean cài đặt dependencies
      - run: npm run build --if-present  # Build React app nếu có script build
      - run: npm test  # Chạy test nếu có

      - name: Deploy to GitHub Pages
        if: success()  # Chỉ deploy nếu các bước trước thành công
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Đường dẫn đến thư mục build React
